### PR TITLE
Fixed #5: Port to GTK3

### LINKED ISSUE #5: Port to GTK+ 3

### PR DESCRIPTION
**Pull request by EmilyOng**
Hi, I have ported the activity to Gtk3, taking into consideration `gdk` and `pango` instances, and pep8 the code!

### CODE REVIEW

**Comment by quozl** [comment]
Did you test?  If so, how?

**Comment by EmilyOng** [comment]
screen shot 2017-12-23 at 5 58 40 pm

seems to be working..

**Comment by EmilyOng** [comment]
Tested with x11vnc, thanks to @cristian99garcia

**Comment by cvgarciarea** [comment]
Screenshot

**Comment by quozl** [comment]
Thanks; two tests observed;
* start up,
* major function.

Reviewed.  No issues.

**Pull request merged**
